on:
  push:
    branches:
    - feature/GithubActions
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: dotnet build --configuration Release

    # Only run unit tests for the Core.* projects
    - name: Test
      run: dotnet test --configuration Release --no-build --filter Axis.Pulsar.Core