on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-*"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build --filter Axis.Pulsar.Core

    # Axis.Pulsar.Core
    - name: Pack
      run: dotnet pack ./Axis.Pulsar.Core/Axis.Pulsar.Core.csproj --configuration Release /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push Axis.Pulsar.Core.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_TOKEN }}

    # Axis.Pulsar.Core.XBNF
    - name: Pack
      run: dotnet pack ./Axis.Pulsar.Core.XBNF/Axis.Pulsar.Core.XBNF.csproj --configuration Release /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push Axis.Pulsar.Core.XBNF.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_TOKEN }}