on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build  

    - name: Find and pack eligible projects
      run: |
        mkdir -p ./build/nupkgs
        for csproj in $(find . -name "*.csproj"); do
          if grep -q "<PackAndPush>true</PackAndPush>" "$csproj"; then
            echo "Packing $csproj"
            dotnet pack "$csproj" -c Release /p:Version=${VERSION} -o ./build/nupkgs
          else
            echo "Skipping $csproj (PublishToNuget not true)"
          fi
        done

    - name: Push packages to GitHub Packages
      run: |
        for nupkg in ./build/nupkgs/*.nupkg; do
          dotnet nuget push "$nupkg" \
            --api-key "${{ secrets.NUGET_API_TOKEN }}" \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate
        done
